# Generated by Django 5.1.7 on 2026-04-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0019_alter_translation_created_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='corpusentry',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='glossaryentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='corpusentry',
            name='target_language',
            field=models.CharField(default='zh', max_length=10),
        ),
        migrations.AddField(
            model_name='glossaryentry',
            name='target_language',
            field=models.CharField(default='zh', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='corpusentry',
            unique_together={('english_text', 'translated_text', 'target_language')},
        ),
        migrations.AlterUniqueTogether(
            name='glossaryentry',
            unique_together={('english_key', 'translated_entry', 'target_language')},
        ),
    ]
